package_name = "audit-userspace"
source_remote = "https://github.com/linux-audit/audit-userspace.git"
remote_type = "git"
download = true
post_download_cmds = ["aclocal", "autoconf", "autoheader", "automake --add-missing", "./autogen.sh"]
version = "v3.0.9"
package_dir = "audit-userspace"
pre_make_cmds = []
make_cmd = "make"
post_make_cmds = []
source_dir = "."