package_name = "libassuan"
source_remote = "https://github.com/gpg/libassuan.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "libassuan-2.5.5"
package_dir = "libassuan"
pre_make_cmds = ["./configure --enable-maintainer-mode --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"