package_name = "libestr"
source_remote = "https://github.com/rsyslog/libestr.git"
remote_type = "git"
download = true
post_download_cmds = []
version = "v0.1.11"
package_dir = "libestr"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "Python"