package_name = "libseccomp"
source_remote = "https://github.com/seccomp/libseccomp.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "v2.5.4"
package_dir = "libseccomp"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"