package_name = "linux-pam"
source_remote = "https://github.com/linux-pam/linux-pam.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "v1.5.2"
package_dir = "linux-pam"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "."