package_name = "util-linux"
source_remote = "https://github.com/util-linux/util-linux.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "v2.38.1"
package_dir = "util-linux"
pre_make_cmds = ["./configure"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"