package_name = "zstd"
source_remote = "https://github.com/facebook/zstd.git"
remote_type = "git"
download = true
post_download_cmds = []
version = "2.75.0"
package_dir = "zstd"
pre_make_cmds = []
make_cmd = "make"
post_make_cmds = []
source_dir = "."