# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Core Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install Java 19
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '19'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip3 install -e .
    - name: Run verification tests
      run: |
        # a hack to allow for docker containers in github actions and ARM
        export JAVA_OPTS="-Djdk.lang.Process.launchMechanism=vfork" 
        ./scripts/ci_verify_pipeline.sh