package_name = "cronie"
source_remote = "https://github.com/cronie-crond/cronie.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "cronie-1.6.1"
package_dir = "cronie"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"