package_name = "dpkg"
source_remote = "https://salsa.debian.org/dpkg-team/dpkg.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen"]
version = "1.20.12"
package_dir = "dpkg"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"