package_name = "kmod"
source_remote = "https://github.com/kmod-project/kmod.git"
remote_type = "git"
download = true
post_download_cmds = ["./autogen.sh"]
version = "v30"
package_dir = "kmod"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "tools"