package_name = "libacl"
source_remote = "http://download.savannah.nongnu.org/releases/acl/acl-2.3.1.tar.xz"
remote_type = "tar"
download = true
post_download_cmds = []
version = ""
package_dir = "acl-2.3.1"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "libacl"
rename_dash_files = true
