package_name = "libselinux"
source_remote = "https://github.com/SELinuxProject/selinux.git"
remote_type = "git"
download = true
post_download_cmds = []
version = "3.4"
package_dir = "selinux/libselinux"
pre_make_cmds = []
make_cmd = "make"
post_make_cmds = []
source_dir = "src"