# XXX: this malware should be a part of the SAILR pipeline
# and this should only be locally copied
package_name = "malware-spyeye"
source_remote = "../../malware/SpyEye"
remote_type = "local"
download = true
post_download_cmds = ["mkdir sailr_decompiled", "cp malware.o sailr_decompiled"]
version = ""
package_dir = "malware-spyeye"
pre_make_cmds = []
make_cmd = ""
post_make_cmds = []
source_dir = ""
skip_compilation = true
skip_file_copy = true