package_name = "shadow"
source_remote = "https://github.com/shadow-maint/shadow.git"
remote_type = "git"
download = true
post_download_cmds = ["aclocal", "autoconf", "autoheader", "automake --add-missing", "autoreconf -v -f --install"]
version = "4.13"
package_dir = "shadow"
pre_make_cmds = ["./configure --quiet"]
make_cmd = "make"
post_make_cmds = []
source_dir = "src"