package_name = "sysvinit"
source_remote = "https://github.com/slicer69/sysvinit.git"
remote_type = "git"
download = true
post_download_cmds = []
version = "3.05"
package_dir = "sysvinit"
pre_make_cmds = []
make_cmd = "make"
post_make_cmds = []
source_dir = "src"