package_name = "zlib"
source_remote = "https://github.com/madler/zlib.git"
remote_type = "git"
download = true
post_download_cmds = []
version = "v1.2.13"
package_dir = "zlib"
pre_make_cmds = ["./configure"]
make_cmd = "make"
post_make_cmds = []
source_dir = "."